#!/usr/bin/env bash
# screenshot.sh — Screenshot capture + GPT Image 2 generation helper
# Usage:
#   screenshot.sh capture <url> <output_path> [playwright|pinchtab]
#   screenshot.sh generate <image_path> --prompt "<text>" [--size WxH] [--method codex|api_key]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

usage() {
  echo "Usage:"
  echo "  $0 capture <url> <output_path> [playwright|pinchtab]"
  echo "  $0 generate <image_path> --prompt \"<text>\" [--size 1536x1024] [--method codex|api_key]"
  echo "  $0 session-init <target_slug>"
  echo "  $0 concepts-generate --session <dir> --round <N> \\"
  echo "      --prompt-1 <p> --label-1 <l> --prompt-2 <p> --label-2 <l> --prompt-3 <p> --label-3 <l>"
  echo "  $0 concepts-choose --session <dir> --round <N> --option <1|2|3>"
  echo "  $0 session-finalize --session <dir> --score-initial <N> --score-final <N>"
  exit 1
}

session_finalize() {
  local session="" score_initial="" score_final=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --session)       session="$2"; shift 2 ;;
      --score-initial) score_initial="$2"; shift 2 ;;
      --score-final)   score_final="$2"; shift 2 ;;
      *) echo "session-finalize: unknown arg '$1'" >&2; exit 1 ;;
    esac
  done
  if [ -z "$session" ] || [ -z "$score_initial" ] || [ -z "$score_final" ]; then
    echo "session-finalize: --session, --score-initial, --score-final required" >&2
    exit 1
  fi
  [ -f "$session/meta.json" ] || { echo "session-finalize: meta.json not found: $session/meta.json" >&2; exit 1; }

  local target stamp
  target=$(jq -r '.target' "$session/meta.json")
  stamp=$(jq -r '.created_at' "$session/meta.json")

  local idx=".screenshot-iterate/INDEX.md"
  mkdir -p .screenshot-iterate
  if [ ! -f "$idx" ]; then
    echo "# Screenshot-Iterate Session Log" > "$idx"
    echo "" >> "$idx"
  fi
  printf -- "- %s — **%s** — %s → %s — \`%s\`\n" "$stamp" "$target" "$score_initial" "$score_final" "$session" >> "$idx"

  local tmp; tmp=$(mktemp)
  jq --argjson si "$score_initial" --argjson sf "$score_final" \
    '.scores = {initial: $si, final: $sf}' "$session/meta.json" > "$tmp"
  mv "$tmp" "$session/meta.json"
}

concepts_choose() {
  local session="" round="" option=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --session) session="$2"; shift 2 ;;
      --round)   round="$2"; shift 2 ;;
      --option)  option="$2"; shift 2 ;;
      *) echo "concepts-choose: unknown arg '$1'" >&2; exit 1 ;;
    esac
  done
  if [ -z "$session" ] || [ -z "$round" ] || [ -z "$option" ]; then
    echo "concepts-choose: --session, --round, --option required" >&2
    exit 1
  fi
  case "$option" in
    1|2|3) ;;
    *) echo "concepts-choose: --option must be 1, 2, or 3" >&2; exit 1 ;;
  esac

  local src="$session/concepts/round-$round/option-$option.png"
  local options_json="$session/concepts/round-$round/options.json"
  [ -f "$src" ] || { echo "concepts-choose: option file not found: $src" >&2; exit 1; }
  [ -f "$options_json" ] || { echo "concepts-choose: options.json not found: $options_json" >&2; exit 1; }
  [ -f "$session/meta.json" ] || { echo "concepts-choose: meta.json not found: $session/meta.json" >&2; exit 1; }

  cp "$src" "$session/concepts/chosen.png"

  local label
  label=$(jq -r --argjson n "$option" '.[] | select(.n == $n) | .label' "$options_json")
  [ -n "$label" ] || { echo "concepts-choose: no label for option $option in $options_json" >&2; exit 1; }

  local tmp; tmp=$(mktemp)
  jq --argjson r "$round" --argjson o "$option" --arg l "$label" \
    '.chosen = {round: $r, option: $o, label: $l}' "$session/meta.json" > "$tmp"
  mv "$tmp" "$session/meta.json"
}

detect_storybook() {
  [ -d .storybook ] && return 0
  [ -f package.json ] || return 1
  jq -e '(.devDependencies.storybook // .dependencies.storybook // empty) | length > 0' \
    package.json >/dev/null 2>&1
}

emit_storybook_story() {
  local session="$1" round="$2"
  detect_storybook || return 0
  mkdir -p src/stories
  local story="src/stories/ScreenshotIterateConcepts.stories.tsx"
  local round_dir="$session/concepts/round-$round"

  # Compute relative path from src/stories/ to the round_dir
  # src/stories/ is 2 levels deep, round_dir is project-relative.
  local rel_prefix="../../"

  {
    echo "// Auto-generated by screenshot-iterate. Do not edit by hand."
    echo "// Round $round"
    echo "import type { Meta, StoryObj } from '@storybook/react';"
    echo ""
    echo "const Concept = ({ src, label }: { src: string; label: string }) => ("
    echo "  <figure style={{ margin: 0 }}>"
    echo "    <img src={src} alt={label} style={{ maxWidth: '100%', display: 'block' }} />"
    echo "    <figcaption style={{ marginTop: 8, fontFamily: 'system-ui' }}>{label}</figcaption>"
    echo "  </figure>"
    echo ");"
    echo ""
    echo "const meta: Meta<typeof Concept> = { title: 'screenshot-iterate/Concepts (round $round)', component: Concept };"
    echo "export default meta;"
    echo ""
    for n in 1 2 3; do
      local label rel label_js
      label=$(jq -r --argjson n "$n" '.[] | select(.n == $n) | .label' "$round_dir/options.json")
      rel="${rel_prefix}${round_dir}/option-$n.png"
      label_js=$(printf '%s' "$label" | sed "s/'/\\\\'/g")
      echo "export const Option$n: StoryObj<typeof Concept> = { args: { src: '$rel', label: '$label_js' } };"
    done
  } > "$story"

  # Add to .gitignore (idempotent), only if inside a git repo
  if [ -d .git ] && ! grep -qxF "src/stories/ScreenshotIterateConcepts.stories.tsx" .gitignore 2>/dev/null; then
    if [ -s .gitignore ] && [ "$(tail -c1 .gitignore)" != "" ]; then
      echo "" >> .gitignore
    fi
    echo "src/stories/ScreenshotIterateConcepts.stories.tsx" >> .gitignore
  fi
}

concepts_generate() {
  local session="" round=""
  local prompts=("" "" "")
  local labels=("" "" "")

  while [ $# -gt 0 ]; do
    case "$1" in
      --session)  session="$2"; shift 2 ;;
      --round)    round="$2"; shift 2 ;;
      --prompt-1) prompts[0]="$2"; shift 2 ;;
      --prompt-2) prompts[1]="$2"; shift 2 ;;
      --prompt-3) prompts[2]="$2"; shift 2 ;;
      --label-1)  labels[0]="$2"; shift 2 ;;
      --label-2)  labels[1]="$2"; shift 2 ;;
      --label-3)  labels[2]="$2"; shift 2 ;;
      *) echo "concepts-generate: unknown arg '$1'" >&2; exit 1 ;;
    esac
  done

  if [ -z "$session" ] || [ -z "$round" ]; then
    echo "concepts-generate: --session and --round are required" >&2
    exit 1
  fi
  for i in 0 1 2; do
    if [ -z "${prompts[$i]}" ] || [ -z "${labels[$i]}" ]; then
      echo "concepts-generate: --prompt-$((i+1)) and --label-$((i+1)) are required" >&2
      exit 1
    fi
  done

  local baseline="$session/baseline.png"
  if [ ! -f "$baseline" ]; then
    echo "concepts-generate: baseline not found at $baseline" >&2
    exit 1
  fi

  local round_dir="$session/concepts/round-$round"
  mkdir -p "$round_dir"

  _gen_one() {
    local idx="$1" prompt="$2" out="$3"
    if [ "${MOCK_GEN:-0}" = "1" ]; then
      cp "$baseline" "$out"
    else
      bash "$0" generate "$baseline" --prompt "$prompt" >/dev/null
      # generate writes to <image>-redesign.png
      local generated="${baseline%.png}-redesign.png"
      mv "$generated" "$out"
    fi
  }

  local pids=()
  for i in 0 1 2; do
    ( _gen_one "$i" "${prompts[$i]}" "$round_dir/option-$((i+1)).png" ) &
    pids+=($!)
  done
  local fail=0
  for pid in "${pids[@]}"; do
    wait "$pid" || fail=1
  done
  if [ "$fail" != "0" ]; then
    echo "concepts-generate: one or more generations failed" >&2
    exit 1
  fi

  jq -n \
    --arg l1 "${labels[0]}" --arg p1 "${prompts[0]}" \
    --arg l2 "${labels[1]}" --arg p2 "${prompts[1]}" \
    --arg l3 "${labels[2]}" --arg p3 "${prompts[2]}" \
    '[
      {n: 1, label: $l1, prompt: $p1, path: "option-1.png"},
      {n: 2, label: $l2, prompt: $p2, path: "option-2.png"},
      {n: 3, label: $l3, prompt: $p3, path: "option-3.png"}
    ]' > "$round_dir/options.json"

  emit_storybook_story "$session" "$round"
}

session_init() {
  local target_slug="$1"
  local stamp; stamp=$(date +%Y-%m-%d_%H-%M-%S)
  local root=".screenshot-iterate/sessions/${stamp}-${target_slug}"
  mkdir -p "$root/concepts" "$root/iterations"
  if [ -d .git ] && ! grep -qxF ".screenshot-iterate/" .gitignore 2>/dev/null; then
    # Ensure the file ends with a newline before appending
    if [ -s .gitignore ] && [ "$(tail -c1 .gitignore)" != "" ]; then
      echo "" >> .gitignore
    fi
    echo ".screenshot-iterate/" >> .gitignore
  fi
  jq -n --arg target "$target_slug" --arg created_at "$stamp" \
    '{target: $target, created_at: $created_at, chosen: null, scores: {}}' \
    > "$root/meta.json"
  echo "$root"
}

detect_tool() {
  if npx playwright --version >/dev/null 2>&1; then
    echo "playwright"
  elif curl -sf http://localhost:9867/health >/dev/null 2>&1; then
    echo "pinchtab"
  else
    echo "none"
  fi
}

detect_img_method() {
  openai_ok=false
  codex_ok=false

  [ -n "${OPENAI_API_KEY:-}" ] && openai_ok=true
  command -v codex >/dev/null 2>&1 && [ -d ~/.codex ] && codex_ok=true

  if [ "$openai_ok" = true ] && [ "$codex_ok" = true ]; then
    echo "both"
  elif [ "$codex_ok" = true ]; then
    echo "codex"
  elif [ "$openai_ok" = true ]; then
    echo "api_key"
  else
    echo "none"
  fi
}

gen_with_api_key() {
  local image="$1" prompt="$2" size="$3" out="$4" model="${5:-gpt-image-2}"

  curl -s https://api.openai.com/v1/images/edits \
    -H "Authorization: Bearer $OPENAI_API_KEY" \
    -F "image=@$image" \
    -F "prompt=$prompt" \
    -F "model=$model" \
    -F "size=$size" \
    -o "$out" 2>/dev/null

  if [ -s "$out" ]; then
    echo "$out"
    return 0
  else
    rm -f "$out"
    return 1
  fi
}

gen_with_codex() {
  local image="$1" prompt="$2" out="$3" timeout_sec="${4:-300}"

  SESSIONS_ROOT="$HOME/.codex/sessions"
  mkdir -p "$SESSIONS_ROOT"

  before="$(mktemp)"; after="$(mktemp)"
  stdout_log="$(mktemp)"; stderr_log="$(mktemp)"
  trap 'rm -f "$before" "$after" "$stdout_log" "$stderr_log"' EXIT

  find "$SESSIONS_ROOT" -type f -name 'rollout-*.jsonl' -print 2>/dev/null | sort > "$before" || true

  instruction="Use the imagegen tool to generate the image for the following request. Use the attached image as visual reference / input for image-to-image.
Requirements: generate the image directly, return only the image, no explanation.

Request:
$prompt"

  # Timeout command detection
  TO=""
  if   command -v timeout  >/dev/null 2>&1; then TO="timeout"
  elif command -v gtimeout >/dev/null 2>&1; then TO="gtimeout"
  fi

  args=(exec --skip-git-repo-check --sandbox read-only --color never --enable image_generation -i "$image")

  set +e
  if [[ -n "$TO" ]]; then
    printf '%s' "$instruction" | "$TO" "$timeout_sec" codex "${args[@]}" >"$stdout_log" 2>"$stderr_log"
  else
    printf '%s' "$instruction" | codex "${args[@]}" >"$stdout_log" 2>"$stderr_log"
  fi
  rc=$?
  set -e

  if [[ $rc -ne 0 ]]; then
    echo "codex exec failed (exit=$rc)" >&2
    return 5
  fi

  find "$SESSIONS_ROOT" -type f -name 'rollout-*.jsonl' -print 2>/dev/null | sort > "$after" || true

  new_sessions_file="$(mktemp)"
  comm -13 "$before" "$after" > "$new_sessions_file" || true

  if [[ ! -s "$new_sessions_file" ]]; then
    echo "No new session file detected" >&2
    return 6
  fi

  set +e
  python3 "$SCRIPT_DIR/extract_image.py" "$out" "$new_sessions_file"
  py_rc=$?
  set -e

  rm -f "$new_sessions_file"

  if [[ $py_rc -ne 0 ]]; then
    echo "Image payload not found in session file" >&2
    return 7
  fi

  echo "$out"
  return 0
}

# -- Main --
[ $# -lt 1 ] && usage
mode="$1"

case "$mode" in
  capture)
    [ $# -lt 3 ] && usage
    shift
    url="$1"
    output="$2"
    tool="${3:-$(detect_tool)}"

    mkdir -p "$(dirname "$output")"

    case "$tool" in
      playwright)
        SURL="$url" SOUT="$output" node -e "
          require('playwright').chromium.launch({headless:true}).then(async b => {
            const p = await b.newPage();
            await p.goto(process.env.SURL,{waitUntil:'networkidle'});
            await p.screenshot({path:process.env.SOUT,fullPage:false});
            await b.close();
          });
        " 2>/dev/null || echo "ERROR: Playwright capture failed"
        ;;
      pinchtab)
        curl -sf "http://localhost:9867/screenshot?url=$(echo "$url" | sed 's/ /%20/g')" \
          > "$output" 2>/dev/null || echo "ERROR: Pinchtab capture failed"
        ;;
      *)
        echo "ERROR: No screenshot tool available. Install Playwright or start pinchtab." >&2
        exit 1
        ;;
    esac
    ;;

  generate)
    [ $# -lt 3 ] && usage
    shift
    image="$1"

    prompt=""
    size="${SCREENSHOT_GENERATE_SIZE:-1536x1024}"
    method="${IMAGE_GEN_METHOD:-auto}"
    output_path="${image%.png}-redesign.png"

    while [ $# -gt 0 ]; do
      case "$1" in
        --prompt)  prompt="$2"; shift 2 ;;
        --size)    size="$2"; shift 2 ;;
        --method)  method="$2"; shift 2 ;;
        *)         shift ;;
      esac
    done

    if [ -z "$prompt" ]; then
      echo "ERROR: --prompt required for generate mode" >&2
      exit 1
    fi

    # Resolve method
    available=$(detect_img_method)

    case "$method" in
      codex|api_key)
        chosen="$method"
        ;;
      auto|both)
        if [ "$available" = "both" ]; then
          echo "Both methods available: Codex CLI (free via ChatGPT subscription)"
          echo "  or OpenAI API key (per-call billing)."
          echo "Which would you like to use?"
          echo ""
          read -r choice || true
          case "${choice,,}" in
            codex*) chosen="codex" ;;
            api*)   chosen="api_key" ;;
            1)      chosen="codex" ;;
            2)      chosen="api_key" ;;
            *)      echo "Defaulting to codex (no extra cost)" && chosen="codex" ;;
          esac
        elif [ "$available" = "codex" ]; then
          chosen="codex"
        elif [ "$available" = "api_key" ]; then
          chosen="api_key"
        else
          echo "ERROR: No image generation method available (need OPENAI_API_KEY or codex CLI)" >&2
          exit 1
        fi
        ;;
      *)
        echo "ERROR: Unknown method '$method'. Use 'codex', 'api_key', or 'auto'." >&2
        exit 1
        ;;
    esac

    # Execute chosen method
    case "$chosen" in
      codex)
        set +e
        result=$(gen_with_codex "$image" "$prompt" "$output_path")
        rc=$?
        set -e
        if [ $rc -eq 0 ]; then
          echo "$result"
        else
          rm -f "$output_path"
          exit $rc
        fi
        ;;
      api_key)
        set +e
        result=$(gen_with_api_key "$image" "$prompt" "$size" "$output_path")
        rc=$?
        set -e
        if [ $rc -eq 0 ]; then
          echo "$result"
        else
          exit 1
        fi
        ;;
    esac
    ;;

  session-init)
    shift
    [ $# -lt 1 ] && usage
    session_init "$@"
    ;;

  concepts-generate)
    shift
    concepts_generate "$@"
    ;;

  concepts-choose)
    shift
    concepts_choose "$@"
    ;;

  session-finalize)
    shift
    session_finalize "$@"
    ;;

  *)
    usage
    ;;
esac
